# Generated by Django 5.1.2 on 2024-10-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.CharField(choices=[('19.0', '19% (DE Standard)'), ('7.0', '7% (DE Reduziert)'), ('20.0', '20% (AT Standard)'), ('10.0', '10% (AT Reduziert)'), ('7.7', '7.7% (CH Standard)'), ('2.5', '2.5% (CH Reduziert)'), ('0.0', 'Keine MwSt.')], default='19.0', max_length=4),
        ),
    ]
