# Generated by Django 5.1.2 on 2024-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoiceitem_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_time'], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_date'], 'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnungen'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id'], 'verbose_name': 'Rechnungsposition', 'verbose_name_plural': 'Rechnungspositionen'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['brand', 'model'], 'verbose_name': 'Fahrzeug', 'verbose_name_plural': 'Fahrzeuge'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Unbezahlt'), ('PAID', 'Bezahlt'), ('CANCELLED', 'Storniert')], default='PENDING', max_length=20),
        ),
    ]
