# Generated by Django 5.1.2 on 2024-11-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Geplant'), ('IN_PROGRESS', 'In Bearbeitung'), ('COMPLETED', 'Abgeschlossen'), ('CANCELLED', 'Storniert')], default='SCHEDULED', max_length=20),
        ),
    ]
